### Include Libraries

In [14]:
import pandas
import numpy as np
import plotly.offline as py
from plotly.offline import *
import plotly.graph_objs as go

init_notebook_mode(connected=True) # render plotly charts in the notebook on the fly

### Have some data to play with

In [1]:
df = pandas.read_csv('dummy_data.csv',sep=',')
print(df.head(3))

   id first_name  last_name                    email  age gender  postcode
0   1       Jory  Colclough    jcolclough0@diigo.com   16      M      3956
1   2     Culver    Aveline  caveline1@microsoft.com   96      M      3557
2   3      Vance     Pridie     vpridie2@comsenz.com   87      M      3361

### Group demo data by Age and Gender, make a line chart

#### Data Munging

In [12]:
# group by gender group by age, return count
age_gender =  df.groupby([ 'gender', 'age']).size().reset_index(name="count")
print(age_gender.head(3))

# make a list of 0 -> 100 for the x axis
ages = list(range(101))
ages_df = pandas.DataFrame(ages, columns = ['age']) # make that a data frame, give it the title Age
print(ages_df.head(3))

# make a data series for women
f = age_gender.loc[age_gender['gender'] == 'F'] # filter for sex = 'F'
f = f.drop('gender', axis=1) # drop gender column
female = ages_df.merge(f, left_on='age', right_on='age', how='left') # left join to ages to get all ages
female['count'].fillna(0, inplace=True) # replace NAN with 0
print(female.head(3))

# make a data series for men
m = age_gender.loc[age_gender['gender'] == 'M'] # filter for sex = 'F'
m = m.drop('gender', axis=1) # drop gender column
male = ages_df.merge(m, left_on='age', right_on='age', how='left') # left join to ages to get all ages
male['count'].fillna(0, inplace=True) # replace NAN with 0
print(male.head(3))

  gender  age  count
0      F   10     46
1      F   11     41
2      F   12     48
   age
0    0
1    1
2    2
   age  count
0    0    0.0
1    1    0.0
2    2    0.0
   age  count
0    0    0.0
1    1    0.0
2    2    0.0

#### Make chart elements

In [21]:
womenSeries = go.Scatter(
    x = female['age'],
    y = female['count'],
    mode = 'columns',
    name = 'Women'
)

menSeries = go.Scatter(
    x = male['age'],
    y = male['count'],
    mode = 'columns',
    name = 'Men'
)

layout = go.Layout(
    xaxis=dict(
        range=[18, 100]
    )
)

#### Make chart

In [22]:
data = [womenSeries, menSeries]

fig = go.Figure(data=data, layout=layout)

py.iplot(fig, filename='line-mode')